// =============================================================================
// File: ProcessStatisticsPO.java
// Generated by JGen Code Generator from INTERSHOP Communications AG.
// Generator template: ORMClass.xpt(checksum: 9a846fb10e9c3b98b1a62ea7a508da27)
// =============================================================================
// The JGen Code Generator software is the property of INTERSHOP Communications AG. 
// Any rights to use are granted under the license agreement. 
// =============================================================================
package com.intershop.component.processstatistics.internal;

import java.util.Date;

import com.intershop.beehive.core.capi.domain.XMLExtensibleObjectPO;
import com.intershop.beehive.core.capi.locking.Process;
import com.intershop.beehive.core.capi.locking.ProcessMgr;
import com.intershop.beehive.core.capi.naming.NamingMgr;
import com.intershop.beehive.orm.capi.common.ORMObjectFactory;
import com.intershop.beehive.orm.capi.description.AttributeDescription;
import com.intershop.component.processstatistics.capi.ProcessStatistics;

/**
 * @see com.intershop.component.processstatistics.capi.ProcessStatistics
 * @generated
 */
public class ProcessStatisticsPO extends XMLExtensibleObjectPO implements ProcessStatistics
{

    /**
     * @generated
     */
    public static AttributeDescription typeAttribute = null;
    /**
     * @generated
     */
    public static AttributeDescription nameAttribute = null;
    /**
     * @generated
     */
    public static AttributeDescription startDateAttribute = null;
    /**
     * @generated
     */
    public static AttributeDescription endDateAttribute = null;
    /**
     * @generated
     */
    public static AttributeDescription resultAttribute = null;

    /**
     * @generated
     */
    public static AttributeDescription processUUIDAttribute = null;

    /**
     * The constructor.
     *
     * @generated
     */
    public ProcessStatisticsPO(ORMObjectFactory factory, ProcessStatisticsPOKey key)
    {
        super(factory, key);
    }

    /**
     * Returns the name of the factory that manages this type of objects. The name can be used to lookup the factory
     * from the NamingMgr.
     *
     * @return the factory name
     * @generated
     */
    public String getFactoryName()
    {
        return getClass().getName();
    }

    /**
     * Loads the state of the object from the database.
     *
     * @deprecated use refresh now
     * @generated
     */
    public void load()
    {
        refresh();
    }

    /**
     * This hook is called whenever the bean has been modified.
     *
     * @generated modifiable
     */
    public void onChange()
    {
        // {{ bean_onchange
        // put your custom onChange code here
        // }} bean_onchange

        super.onChange();
    }

    /**
     * Returns the value of attribute 'type'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getType()
     *
     * @return the value of the attribute 'type'
     * @generated
     */
    public String getType()
    {
        String value = (String)getAttributeValue(typeAttribute);
        return (value != null) ? value : "";
    }

    /**
     * Sets the value of the attribute 'type'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getType()
     *
     * @param aValue
     *            the new value of the attribute
     * @generated
     */
    public void setType(String aValue)
    {

        if (setAttributeValue(typeAttribute, aValue))
        {
            onChange();
        }
    }

    /**
     * Checks whether the value of the attribute 'type' is null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getType()
     *
     * @return true if the value of attribute 'type' is null, false otherwise
     * @generated
     */
    public boolean getTypeNull()
    {
        return (getAttributeValue(typeAttribute) == null);
    }

    /**
     * Sets the value of the attribute 'type' to null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getType()
     *
     * @param aFlag
     *            meaningless
     * @generated
     */
    public void setTypeNull(boolean aFlag)
    {

        if (setAttributeValue(typeAttribute, null))
        {

            onChange();
        }
    }

    /**
     * Returns the value of attribute 'name'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getName()
     *
     * @return the value of the attribute 'name'
     * @generated
     */
    public String getName()
    {
        String value = (String)getAttributeValue(nameAttribute);
        return (value != null) ? value : "";
    }

    /**
     * Sets the value of the attribute 'name'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getName()
     *
     * @param aValue
     *            the new value of the attribute
     * @generated
     */
    public void setName(String aValue)
    {

        if (setAttributeValue(nameAttribute, aValue))
        {
            onChange();
        }
    }

    /**
     * Checks whether the value of the attribute 'name' is null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getName()
     *
     * @return true if the value of attribute 'name' is null, false otherwise
     * @generated
     */
    public boolean getNameNull()
    {
        return (getAttributeValue(nameAttribute) == null);
    }

    /**
     * Sets the value of the attribute 'name' to null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getName()
     *
     * @param aFlag
     *            meaningless
     * @generated
     */
    public void setNameNull(boolean aFlag)
    {

        if (setAttributeValue(nameAttribute, null))
        {

            onChange();
        }
    }

    /**
     * Returns the value of attribute 'startDate'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getStartDate()
     *
     * @return the value of the attribute 'startDate'
     * @generated
     */
    public Date getStartDate()
    {
        return (Date)getAttributeValue(startDateAttribute);
    }

    /**
     * Sets the value of the attribute 'startDate'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getStartDate()
     *
     * @param aValue
     *            the new value of the attribute
     * @generated
     */
    public void setStartDate(Date aValue)
    {

        if (setAttributeValue(startDateAttribute, aValue))
        {
            onChange();
        }
    }

    /**
     * Checks whether the value of the attribute 'startDate' is null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getStartDate()
     *
     * @return true if the value of attribute 'startDate' is null, false otherwise
     * @generated
     */
    public boolean getStartDateNull()
    {
        return (getAttributeValue(startDateAttribute) == null);
    }

    /**
     * Sets the value of the attribute 'startDate' to null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getStartDate()
     *
     * @param aFlag
     *            meaningless
     * @generated
     */
    public void setStartDateNull(boolean aFlag)
    {

        if (setAttributeValue(startDateAttribute, null))
        {

            onChange();
        }
    }

    /**
     * Returns the value of attribute 'endDate'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getEndDate()
     *
     * @return the value of the attribute 'endDate'
     * @generated
     */
    public Date getEndDate()
    {
        return (Date)getAttributeValue(endDateAttribute);
    }

    /**
     * Sets the value of the attribute 'endDate'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getEndDate()
     *
     * @param aValue
     *            the new value of the attribute
     * @generated
     */
    public void setEndDate(Date aValue)
    {

        if (setAttributeValue(endDateAttribute, aValue))
        {
            onChange();
        }
    }

    /**
     * Checks whether the value of the attribute 'endDate' is null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getEndDate()
     *
     * @return true if the value of attribute 'endDate' is null, false otherwise
     * @generated
     */
    public boolean getEndDateNull()
    {
        return (getAttributeValue(endDateAttribute) == null);
    }

    /**
     * Sets the value of the attribute 'endDate' to null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getEndDate()
     *
     * @param aFlag
     *            meaningless
     * @generated
     */
    public void setEndDateNull(boolean aFlag)
    {

        if (setAttributeValue(endDateAttribute, null))
        {

            onChange();
        }
    }

    /**
     * Returns the value of attribute 'result'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getResult()
     *
     * @return the value of the attribute 'result'
     * @generated
     */
    public String getResult()
    {
        String value = (String)getAttributeValue(resultAttribute);
        return (value != null) ? value : "";
    }

    /**
     * Sets the value of the attribute 'result'.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getResult()
     *
     * @param aValue
     *            the new value of the attribute
     * @generated
     */
    public void setResult(String aValue)
    {

        if (setAttributeValue(resultAttribute, aValue))
        {
            onChange();
        }
    }

    /**
     * Checks whether the value of the attribute 'result' is null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getResult()
     *
     * @return true if the value of attribute 'result' is null, false otherwise
     * @generated
     */
    public boolean getResultNull()
    {
        return (getAttributeValue(resultAttribute) == null);
    }

    /**
     * Sets the value of the attribute 'result' to null.
     * <p>
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getResult()
     *
     * @param aFlag
     *            meaningless
     * @generated
     */
    public void setResultNull(boolean aFlag)
    {

        if (setAttributeValue(resultAttribute, null))
        {

            onChange();
        }
    }

    /**
     * Returns the value of attribute 'processUUID'.
     * <p>
     * UUID of the underlying Process.
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getProcess()
     *
     * @return the value of the attribute 'processUUID'
     * @generated
     */
    public String getProcessUUID()
    {
        String value = (String)getAttributeValue(processUUIDAttribute);
        return (value != null) ? value : "";
    }

    /**
     * Sets the value of the attribute 'processUUID'.
     * <p>
     * UUID of the underlying Process.
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getProcess()
     *
     * @param aValue
     *            the new value of the attribute
     * @generated
     */
    public void setProcessUUID(String aValue)
    {

        if (setAttributeValue(processUUIDAttribute, aValue))
        {
            onChange();
        }
    }

    /**
     * Checks whether the value of the attribute 'processUUID' is null.
     * <p>
     * UUID of the underlying Process.
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getProcess()
     *
     * @return true if the value of attribute 'processUUID' is null, false otherwise
     * @generated
     */
    public boolean getProcessUUIDNull()
    {
        return (getAttributeValue(processUUIDAttribute) == null);
    }

    /**
     * Sets the value of the attribute 'processUUID' to null.
     * <p>
     * UUID of the underlying Process.
     * 
     * @see com.intershop.component.processstatistics.capi.ProcessStatistics#getProcess()
     *
     * @param aFlag
     *            meaningless
     * @generated
     */
    public void setProcessUUIDNull(boolean aFlag)
    {

        if (setAttributeValue(processUUIDAttribute, null))
        {

            onChange();
        }
    }

    /**
     * Returns the Process that is associated with this object through a weak relation.
     * <p>
     *
     * @return the associated object, or null if no instance is associated
     * @generated
     */
    public Process getProcess()
    {
        if (getProcessUUIDNull())
        {
            return null;
        }

        ProcessMgr factory = (ProcessMgr)NamingMgr.getInstance().lookupManager(ProcessMgr.REGISTRY_NAME);

        return (Process)factory.resolveProcessFromID(getProcessUUID());
    }

    /**
     * Sets the Process to be associated with this object. The association is established through a weak relation.
     * <p>
     *
     * @param process
     *            the Process to be associated with this object
     * @generated
     */
    public void setProcess(Process process)
    {
        if (process == null)
        {
            setProcessUUIDNull(true);
        }
        else
        {
            setProcessUUID(process.getUUID());
        }
    }

}
